Arithmetics done
TomsStasulans/06-2021 pull request #2
Opened 2021-11-27 20:24 UTC by TomsStasulans

2021-11-28 20:29 UTC, ausmoons requested changes

2021-11-28 20:29 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise 1/Program.cs
> +            } else if (firstInt - secondInt == 15 || firstInt + secondInt == 15)
Else if jaunā rindā

2021-11-28 20:29 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise 2/Program.cs
> +            } else
Else jaunā rindā

2021-11-28 20:29 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise 5/Program.cs
> +            Random rand = new Random();
Rand?

2021-11-28 20:29 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise 8/Program.cs
> +            {
Šim varēja atsevišķu validāciju izveidot, kur padod employee, jo 3x raksti vienu un to pašu

2021-11-28 20:29 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/SumAverageRunningInt/Program.cs
> +
Pietiek ar vienu tukšu rindu

2021-11-29 08:25 UTC, TomsStasulans commented on csharp-basics/exercises/Arithmetic/Exercise 8/Program.cs
> +            {
Laikam ir.

2021-11-29 08:27 UTC, TomsStasulans commented on csharp-basics/exercises/Arithmetic/SumAverageRunningInt/Program.cs
> +
Man kompī rādās viena tukša rinda. Noseivošu un commitošu. Cerams būs. Paldies par kļūdu labojumiem!!!

2021-11-29 19:56 UTC, ausmoons approved these changes

2021-11-29 19:56 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise 1/Program.cs
> +
Šādas liekās atstarpes vajadzētu ņemt ārā. Ar ctrl+f un tad ieraskti 2 spacesu.. tā varēsi atrasti tādas vietas. Ir arī extensions priekš tā

2021-11-30 06:28 UTC, merged