Arrays
TomsStasulans/06-2021 pull request #4
Opened 2021-12-01 07:43 UTC by TomsStasulans

I think it is done.

2021-12-01 17:13 UTC, ausmoons requested changes

2021-12-01 17:13 UTC, ausmoons commented on csharp-basics/exercises/Arrays/Arrays/Exercise 7/Program.cs
> +                return true;
Vienādos if var apvienot zem viena, lai nav visu laiku jāraksta return true

2021-12-01 20:00 UTC, TomsStasulans commented on csharp-basics/exercises/Arrays/Arrays/Exercise 7/Program.cs
> +                return true;
Paldies. Nākošreiz tā arī darīšu.

2021-12-02 18:45 UTC, ausmoons approved these changes

2021-12-03 07:57 UTC, merged