Tests
TomsStasulans/06-2021 pull request #9
Opened 2022-01-02 13:13 UTC by TomsStasulans

Tests tested

2022-01-02 13:50 UTC, ausmoons requested changes

2022-01-02 13:50 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CalculateArea.Tests/Geometry.Tests.cs
> +            var result = Math.Round(Geometry.AreaOfCircle(radius), 1);
Metodei jau vajadzētu atgriezt rounded, ja tu gribi tādu rezultātu

2022-01-02 13:50 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/CalculateArea.Tests/Geometry.Tests.cs
> +        public void TriangleArea_5_10_ShouldReturn25()
AreaOfTriangle_5groundAnd10Height_Returns25
MetodesNosaukums_KoPadod_KoSagaida

2022-01-02 13:50 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Exercise1.Tests/Exercise1.Tests.cs
> +        public void GetTwoNumbers_TwoNumbers_IfAnyIsFifteenShouldReturnTrue()
IsAnyNumberFifteen_NumberIsFifteen_ReturnsTrue. Pārskati visur testu nosaukumus

2022-01-07 12:19 UTC, TomsStasulans commented
Šodien jauka diena.

2022-01-07 18:20 UTC, ausmoons approved these changes

2022-01-08 07:05 UTC, merged